name: Trigger Jenkins on push to master

on:
  push:
    branches:
      - master

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          CRUMB=$(curl -s 'http://34.88.175.96:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)' | sed 's/[\r\n]//g')
          curl -X POST -u "admin:admin" -H "$CRUMB" http://34.88.175.96:8080/job/Trigger%20Airflow%20DAG/build?token=jenkins_job


