name: Trigger Jenkins on push to master

on:
  push:
    branches:
      - master

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          curl -X POST http://34.88.175.96:8080/job/Trigger%20Airflow%20DAG/build?token=jenkins_job
